In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('Dataset for Data Analytics.csv')

In [10]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [5]:
df.shape

(1200, 14)

In [6]:
df.dtypes

OrderID                str
Date                   str
CustomerID             str
Product                str
Quantity             int64
UnitPrice          float64
ShippingAddress        str
PaymentMethod          str
OrderStatus            str
TrackingNumber         str
ItemsInCart          int64
CouponCode             str
ReferralSource         str
TotalPrice         float64
dtype: object

In [23]:
df['Date'].dtype

dtype('<M8[us]')

In [20]:
df['Date'].head()

0   2023-01-04
1   2024-08-23
2   2024-02-27
3   2023-10-15
4   2025-05-08
Name: Date, dtype: datetime64[us]

In [8]:
#Overall Statistics
df[['Quantity','UnitPrice','ItemsInCart','TotalPrice']].describe()

          Quantity    UnitPrice  ItemsInCart   TotalPrice
count  1200.000000  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750     5.485000  1053.968300
std       1.407557   197.177146     2.281983   819.856558
min       1.000000    11.390000     1.000000    11.390000
25%       2.000000   186.062500     4.000000   410.520000
50%       3.000000   364.210000     5.000000   823.615000
75%       4.000000   521.570000     7.000000  1578.475000
max       5.000000   699.930000    10.000000  3456.400000

In [ ]:
#Phase1-Basic Statistics:

In [13]:
#Mean
print("Quantity ordered:",round(df['Quantity'].mean(),2))
print(" Unit Price:", round(df['UnitPrice'].mean(), 2))
print("Items In Cart:",round(df['ItemsInCart'].mean(),2))
print("Total Price:",round(df['TotalPrice'].mean(),2))

Quantity ordered: 2.95
 Unit Price: 356.41
Items In Cart: 5.48
Total Price: 1053.97

In [15]:
#Median
print("Quantity ordered:",round(df['Quantity'].median(),2))
print("Unit Price:",round(df['UnitPrice'].median(),2))
print("Items In Cart:",round(df['ItemsInCart'].median(),2))
print("Total Price:",round(df['TotalPrice'].median(),2))

Quantity ordered: 3.0
Unit Price: 364.21
Items In Cart: 5.0
Total Price: 823.62

In [16]:
#Count
print("Orders:",df['OrderID'].count())
print("Unique Customers:",df['CustomerID'].nunique())
print("Unique Products:", df['Product'].nunique())

Orders: 1200
Unique Customers: 1189
Unique Products: 7

In [ ]:

#Phase2 - Trend Analysis

In [4]:
#Most Popular Products
df['Product'].value_counts()

Product
Printer    181
Tablet     179
Chair      178
Laptop     173
Desk       170
Monitor    163
Phone      156
Name: count, dtype: int64

In [6]:
#Most Used Payment Method
df['PaymentMethod'].value_counts()

PaymentMethod
Online         258
Cash           246
Credit Card    234
Debit Card     232
Gift Card      230
Name: count, dtype: int64

In [7]:
#Order Status Breakdown
df['OrderStatus'].value_counts()

OrderStatus
Cancelled    250
Returned     247
Pending      237
Shipped      235
Delivered    231
Name: count, dtype: int64

In [8]:
#Top Referral Sources
df['ReferralSource'].value_counts()

ReferralSource
Instagram    259
Email        250
Google       241
Facebook     228
Referral     222
Name: count, dtype: int64

In [ ]:
#Revenue By Product
revenue_by_product=df.groupby('Product')['TotalPrice'].sum().sort_values(ascending=False)
print(revenue_by_product.round(2))

Product
Chair      195620.11
Printer    195612.61
Laptop     192126.56
Tablet     186568.95
Monitor    175651.41
Desk       167459.93
Phone      151722.39
Name: TotalPrice, dtype: float64

In [10]:
#Average Order Value By Payment Method
avg_by_payment = df.groupby('PaymentMethod')['TotalPrice'].mean().sort_values(ascending=False)
print(avg_by_payment.round(2))

PaymentMethod
Credit Card    1127.55
Gift Card      1070.97
Cash           1056.04
Online         1017.22
Debit Card     1001.56
Name: TotalPrice, dtype: float64

In [24]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=False)

In [29]:
#Monthly Order Trend
monthly_orders = df.groupby('Month')['OrderID'].count()
print(monthly_orders.head())

Month
2023-01    47
2023-02    37
2023-03    43
2023-04    31
2023-05    49
Freq: M, Name: OrderID, dtype: int64

In [31]:
#OUTLIERS IN UNIT PRICE 
Q1_unit = df['UnitPrice'].quantile(0.25)
Q3_unit = df['UnitPrice'].quantile(0.75)
IQR_unit = Q3_unit - Q1_unit
lower_unit = Q1_unit - 1.5 * IQR_unit
upper_unit = Q3_unit + 1.5 * IQR_unit
outliers_unit = df[(df['UnitPrice'] < lower_unit) | (df['UnitPrice'] > upper_unit)]


print("Q1:",round(Q1_unit,2))
print("Q3:",round(Q3_unit,2))
print("IQR",round(IQR_unit,2))
print("Lower Bound:",round(lower_unit,2))
print("Upper Bound:",round(upper_unit, 2))
print("Number of Outliers:",len(outliers_unit))

Q1: 186.06
Q3: 521.57
IQR 335.51
Lower Bound: -317.2
Upper Bound: 1024.83
Number of Outliers: 0

In [32]:
#OUTLIERS IN TOTAL PRICE
Q1_total = df['TotalPrice'].quantile(0.25)
Q3_total = df['TotalPrice'].quantile(0.75)
IQR_total = Q3_total - Q1_total
lower_total = Q1_total - 1.5 * IQR_total
upper_total = Q3_total + 1.5 * IQR_total
outliers_total = df[(df['TotalPrice'] < lower_total) | (df['TotalPrice'] > upper_total)]


print("Q1:",round(Q1_total, 2))
print("Q3:", round(Q3_total, 2))
print("IQR:",round(IQR_total, 2))
print("Lower Bound",round(lower_total, 2))
print("Upper Bound:",round(upper_total, 2))
print("Number of Outliers:", len(outliers_total))

Q1: 410.52
Q3: 1578.48
IQR: 1167.96
Lower Bound -1341.41
Upper Bound: 3330.41
Number of Outliers: 8

In [33]:
#OUTLIERS IN QUANTITY
Q1_qty = df['Quantity'].quantile(0.25)
Q3_qty = df['Quantity'].quantile(0.75)
IQR_qty = Q3_qty - Q1_qty
lower_qty = Q1_qty - 1.5 * IQR_qty
upper_qty = Q3_qty + 1.5 * IQR_qty
outliers_qty = df[(df['Quantity'] < lower_qty) | (df['Quantity'] > upper_qty)]


print("Q1:",round(Q1_qty, 2))
print("Q3:",round(Q3_qty, 2))
print("IQR:", round(IQR_qty, 2))
print("Lower Bound:",round(lower_qty, 2))
print("Upper Bound:", round(upper_qty, 2))
print("Number of Outliers:", len(outliers_qty))

Q1: 2.0
Q3: 4.0
IQR: 2.0
Lower Bound: -1.0
Upper Bound: 7.0
Number of Outliers: 0

In [34]:

#Phase4-THE SO WHAT SUMMARY

# FINDING 1 - BASIC STATISTICS
print(f"Average order value is ${round(df['TotalPrice'].mean(), 2)}")
print(f"Median order value is ${round(df['TotalPrice'].median(), 2)}")
print(f"Highest order value is ${round(df['TotalPrice'].max(), 2)}")
print(f"Lowest order value is ${round(df['TotalPrice'].min(), 2)}")

# FINDING 2 - BEST SELLING PRODUCT
best_product = df['Product'].value_counts().idxmax()
print(f"Most ordered product is: {best_product}")
top_revenue_product = df.groupby('Product')['TotalPrice'].sum().idxmax()
print(f"Product generating most revenue: {top_revenue_product}")

# FINDING 3 - PAYMENT METHOD
top_payment = df['PaymentMethod'].value_counts().idxmax()
print(f"Most used payment method: {top_payment}")
highest_spend_payment = df.groupby('PaymentMethod')['TotalPrice'].mean().idxmax()
print(f"Payment method with highest average spend: {highest_spend_payment}")

# FINDING 4 - ORDER STATUS
top_status = df['OrderStatus'].value_counts().idxmax()
cancelled = df[df['OrderStatus'] == 'Cancelled']['OrderID'].count()
returned = df[df['OrderStatus'] == 'Returned']['OrderID'].count()
delivered = df[df['OrderStatus'] == 'Delivered']['OrderID'].count()
print(f"Most common order status: {top_status}")
print(f"Total Cancelled orders: {cancelled}")
print(f"Total Returned orders: {returned}")
print(f"Total Delivered orders: {delivered}")

# FINDING 5 - REFERRAL SOURCE
top_referral = df['ReferralSource'].value_counts().idxmax()
print(f"Top referral source bringing most customers: {top_referral}")

# FINDING 6 - MONTHLY TREND
df['Month'] = pd.to_datetime(df['Date']).dt.to_period('M')
monthly = df.groupby('Month')['OrderID'].count()
best_month = monthly.idxmax()
worst_month = monthly.idxmin()
print(f"Busiest month: {best_month} with {monthly.max()} orders")
print(f"Quietest month: {worst_month} with {monthly.min()} orders")

# FINDING 7 - OUTLIERS
print(f"UnitPrice outliers found: {len(outliers_unit)}")
print(f"TotalPrice outliers found: {len(outliers_total)}")
print(f"Quantity outliers found: {len(outliers_qty)}")

Average order value is $1053.97
Median order value is $823.62
Highest order value is $3456.4
Lowest order value is $11.39
Most ordered product is: Printer
Product generating most revenue: Chair
Most used payment method: Online
Payment method with highest average spend: Credit Card
Most common order status: Cancelled
Total Cancelled orders: 250
Total Returned orders: 247
Total Delivered orders: 231
Top referral source bringing most customers: Instagram
Busiest month: 2024-06 with 53 orders
Quietest month: 2025-01 with 27 orders
UnitPrice outliers found: 0
TotalPrice outliers found: 8
Quantity outliers found: 0